apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-apps-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-apps
  template:
    metadata:
      labels:
        app: register-apps
    spec:
      containers:
        - name: register-apps
          image: ganavi23/register-apps-pipeline:1.0.0-18
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
