apiVersion: v1
kind: Service
metadata:
  name: register-apps-service
  labels:
    app: register-apps 
spec:
  selector:
    app: register-apps

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
